#!/bin/bash
# No-LiDAR test: fake sensors + saved map, run Nav2 + decision stack
# Requires: existing map files (e.g. map.yaml + map.pgm under ~/nav_ws or ~/Desktop/map)

set -e
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SENTRY_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# Map path (edit for your setup)
# Default: project RMUL arena map (university league field)
MAP_YAML="${MAP_YAML:-$SENTRY_ROOT/rm_navigation_ws/src/rm_nav_bringup/map/RMUL.yaml}"
NAV_PARAMS="${NAV_PARAMS:-$SENTRY_ROOT/my_nav2_params.yaml}"

echo "=========================================="
echo "  No-LiDAR test — Nav2 + decision"
echo "  Map: $MAP_YAML"
echo "=========================================="
echo ""
echo "⚠️  If you get Permission denied writing ~/.ros/log, run:"
echo "    sudo chown -R \$(whoami):\$(whoami) ~/.ros"
echo ""
echo "⚠️  If you see setup.sh not found, open a new shell or run:"
echo "    unset AMENT_PREFIX_PATH COLCON_PREFIX_PATH"
echo ""
echo "Open 5 terminals and run in order (note: steps 1–4 + ref/5):"
echo ""
echo "[Terminal 1] Fake sensors:"
echo "  unset AMENT_PREFIX_PATH COLCON_PREFIX_PATH  # optional, avoid workspace pollution"
echo "  source /opt/ros/humble/setup.bash"
echo "  python3 $SCRIPT_DIR/fake_sensors_for_test.py"
echo ""
echo "[Terminal 2] Map server + Nav2:"
echo "  source /opt/ros/humble/setup.bash"
echo "  source $SENTRY_ROOT/install/setup.bash   # if built in this repo"
echo "  ros2 launch nav2_bringup bringup_launch.py \\"
echo "    use_sim_time:=False \\"
echo "    map:=$MAP_YAML \\"
echo "    params_file:=$NAV_PARAMS"
echo ""
echo "[Terminal 3] Behavior-tree comm adapter:"
echo "  source /opt/ros/humble/setup.bash"
echo "  source $SENTRY_ROOT/rm_vision_ws/install/setup.bash"
echo "  source $SENTRY_ROOT/rm_decision_ws/install/setup.bash"
echo "  python3 $SENTRY_ROOT/scripts/bt_comm_adapter.py"
echo ""
echo "[Terminal 4] Decision (behavior tree):"
echo "  source /opt/ros/humble/setup.bash"
echo "  source $SENTRY_ROOT/rm_vision_ws/install/setup.bash"
echo "  source $SENTRY_ROOT/rm_decision_ws/install/setup.bash"
echo "  ros2 launch rm_behavior_tree rm_behavior_tree.launch.py \\"
echo "    style:=retreat_attack_left use_sim_time:=False"
echo ""
echo "[Terminal 5] Mock referee data:"
echo "  source $SENTRY_ROOT/rm_decision_ws/install/setup.bash"
echo "  source $SENTRY_ROOT/rm_vision_ws/install/setup.bash"
echo "  ros2 topic pub -r 1 /game_status rm_decision_interfaces/msg/GameStatus \\"
echo "    '{game_progress: 4, stage_remain_time: 180}'"
echo ""
echo "Or run: $SENTRY_ROOT/rm_decision_ws/rm_decision_interfaces/publish_script.sh"
echo ""
echo "Default adapter uses vx/vy only; Nav2 angular z (wz) is ignored."
echo ""
