FROM ros:humble-ros-base

# FishROS one-step mirror setup
RUN apt update \ 
    && apt install wget python3-yaml -y  \
    && echo "chooses:\n" > fish_install.yaml \
    && echo "- {choose: 5, desc: 'One-step: system mirrors (switch Ubuntu apt sources, all Ubuntu versions)'}\n" >> fish_install.yaml \
    && echo "- {choose: 2, desc: Switch system sources and remove third-party sources}\n" >> fish_install.yaml \
    && echo "- {choose: 1, desc: Add ROS/ROS2 apt sources}\n" >> fish_install.yaml \
    && wget http://fishros.com/install  -O fishros && /bin/bash fishros \
    && rm -rf /var/lib/apt/lists/*  /tmp/* /var/tmp/* \
    && apt-get clean && apt autoclean 

# Initialize rosdepc
RUN apt-get update && apt-get install python3-pip -y && \
    pip install rosdepc && \
    sudo rosdepc init  && \
    rosdepc update

# clone projects
RUN git clone https://gitee.com/SMBU-POLARBEAR/PB_RM_Vision

# create workspace
WORKDIR /PB_RM_Vision/

# install dependencies and some tools
RUN rosdepc install -r --from-paths src --ignore-src --rosdistro $ROS_DISTRO -y && \
    apt-get install ros-humble-foxglove-bridge wget htop vim -y && \
    rm -rf /var/lib/apt/lists/*

# setup zsh
RUN sh -c "$(wget -O- https://mirror.ghproxy.com/https://github.com/deluan/zsh-in-docker/releases/download/v1.1.5/zsh-in-docker.sh)" -- \
    -t jispwoso -p git \
    -p https://mirror.ghproxy.com/https://github.com/zsh-users/zsh-autosuggestions \
    -p https://mirror.ghproxy.com/https://github.com/zsh-users/zsh-syntax-highlighting && \
    chsh -s /bin/zsh && \
    rm -rf /var/lib/apt/lists/*

# build
RUN . /opt/ros/humble/setup.sh && colcon build --symlink-install

# setup .zshrc
RUN echo 'export TERM=xterm-256color\n\
source /PB_RM_Vision/install/setup.zsh\n\
eval "$(register-python-argcomplete3 ros2)"\n\
eval "$(register-python-argcomplete3 colcon)"\n'\
>> /root/.zshrc

# source entrypoint setup
RUN sed --in-place --expression \
      '$isource "/PB_RM_Vision/install/setup.bash"' \
      /ros_entrypoint.sh